// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingested_forms.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingIngestedForms = `-- name: ClaimPendingIngestedForms :many
WITH claimed AS (
    SELECT id FROM ingested_forms
    WHERE status = 'pending' AND attempt_count < $1::int
    ORDER BY created_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
UPDATE ingested_forms
SET status = 'processing', updated_at = now()
FROM claimed
WHERE ingested_forms.id = claimed.id
RETURNING ingested_forms.id, ingested_forms.application_reference, ingested_forms.session_id, ingested_forms.raw_payload, ingested_forms.status, ingested_forms.last_error, ingested_forms.attempt_count, ingested_forms.created_at, ingested_forms.updated_at
`

type ClaimPendingIngestedFormsParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	BatchSize   int32 `json:"batch_size"`
}

// Claims and marks 'processing' in one statement so no row lock is held
// during the slow geocode/email network calls that follow.
func (q *Queries) ClaimPendingIngestedForms(ctx context.Context, arg ClaimPendingIngestedFormsParams) ([]IngestedForm, error) {
	rows, err := q.db.Query(ctx, claimPendingIngestedForms, arg.MaxAttempts, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestedForm
	for rows.Next() {
		var i IngestedForm
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationReference,
			&i.SessionID,
			&i.RawPayload,
			&i.Status,
			&i.LastError,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngestedFormByApplicationReference = `-- name: GetIngestedFormByApplicationReference :one
SELECT id, application_reference, session_id, raw_payload, status, last_error, attempt_count, created_at, updated_at FROM ingested_forms
WHERE application_reference = $1
`

func (q *Queries) GetIngestedFormByApplicationReference(ctx context.Context, applicationReference string) (IngestedForm, error) {
	row := q.db.QueryRow(ctx, getIngestedFormByApplicationReference, applicationReference)
	var i IngestedForm
	err := row.Scan(
		&i.ID,
		&i.ApplicationReference,
		&i.SessionID,
		&i.RawPayload,
		&i.Status,
		&i.LastError,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIngestedForm = `-- name: InsertIngestedForm :one
INSERT INTO ingested_forms (application_reference, session_id, raw_payload)
VALUES ($1, $2, $3)
ON CONFLICT (application_reference) DO NOTHING
RETURNING id, application_reference, session_id, raw_payload, status, last_error, attempt_count, created_at, updated_at
`

type InsertIngestedFormParams struct {
	ApplicationReference string `json:"application_reference"`
	SessionID            string `json:"session_id"`
	RawPayload           []byte `json:"raw_payload"`
}

// No row returned (pgx.ErrNoRows) means application_reference already
// existed — a duplicate delivery, dropped silently (first-write-wins).
func (q *Queries) InsertIngestedForm(ctx context.Context, arg InsertIngestedFormParams) (IngestedForm, error) {
	row := q.db.QueryRow(ctx, insertIngestedForm, arg.ApplicationReference, arg.SessionID, arg.RawPayload)
	var i IngestedForm
	err := row.Scan(
		&i.ID,
		&i.ApplicationReference,
		&i.SessionID,
		&i.RawPayload,
		&i.Status,
		&i.LastError,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIngestedFormFailed = `-- name: MarkIngestedFormFailed :exec
UPDATE ingested_forms
SET status = 'failed',
    last_error = $2,
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
`

type MarkIngestedFormFailedParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkIngestedFormFailed(ctx context.Context, arg MarkIngestedFormFailedParams) error {
	_, err := q.db.Exec(ctx, markIngestedFormFailed, arg.ID, arg.LastError)
	return err
}

const markIngestedFormSucceeded = `-- name: MarkIngestedFormSucceeded :exec
UPDATE ingested_forms
SET status = 'succeeded', last_error = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkIngestedFormSucceeded(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markIngestedFormSucceeded, id)
	return err
}

const reclaimStaleProcessing = `-- name: ReclaimStaleProcessing :execrows
UPDATE ingested_forms
SET status = 'pending', updated_at = now()
WHERE status = 'processing' AND updated_at < now() - $1::interval
`

// Resets rows orphaned by a worker crash mid-row (claimed but never
// finished) back to 'pending' after they've sat in 'processing' too long.
func (q *Queries) ReclaimStaleProcessing(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleProcessing, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueForRetry = `-- name: RequeueForRetry :one
UPDATE ingested_forms
SET status = 'pending', attempt_count = 0, updated_at = now()
WHERE application_reference = $1 AND status = 'failed'
RETURNING id, application_reference, session_id, raw_payload, status, last_error, attempt_count, created_at, updated_at
`

// Only a 'failed' row can be retried; raw_payload is untouched, so the next
// worker pass re-parses it with whatever code fix has since shipped.
// attempt_count is reset so the claim query's attempt_count < max_attempts
// filter doesn't skip a row that had already hit max_attempts.
func (q *Queries) RequeueForRetry(ctx context.Context, applicationReference string) (IngestedForm, error) {
	row := q.db.QueryRow(ctx, requeueForRetry, applicationReference)
	var i IngestedForm
	err := row.Scan(
		&i.ID,
		&i.ApplicationReference,
		&i.SessionID,
		&i.RawPayload,
		&i.Status,
		&i.LastError,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
