// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IngestedForm struct {
	ID                   int64              `json:"id"`
	ApplicationReference string             `json:"application_reference"`
	SessionID            string             `json:"session_id"`
	RawPayload           []byte             `json:"raw_payload"`
	Status               string             `json:"status"`
	LastError            pgtype.Text        `json:"last_error"`
	AttemptCount         int32              `json:"attempt_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TransformedForm struct {
	ID                   int64              `json:"id"`
	IngestedFormID       int64              `json:"ingested_form_id"`
	ApplicationReference string             `json:"application_reference"`
	SessionID            string             `json:"session_id"`
	FirstName            string             `json:"first_name"`
	LastName             string             `json:"last_name"`
	Email                string             `json:"email"`
	Gender               string             `json:"gender"`
	DateOfBirth          pgtype.Date        `json:"date_of_birth"`
	PhoneNumber          pgtype.Text        `json:"phone_number"`
	MobileNumber         string             `json:"mobile_number"`
	AddressLine1         string             `json:"address_line_1"`
	AddressLine2         string             `json:"address_line_2"`
	AddressLine3         pgtype.Text        `json:"address_line_3"`
	Postcode             string             `json:"postcode"`
	Country              string             `json:"country"`
	Longitude            float64            `json:"longitude"`
	Latitude             float64            `json:"latitude"`
	EmailedAt            pgtype.Timestamptz `json:"emailed_at"`
	ReadyAt              pgtype.Timestamptz `json:"ready_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
