// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Claims and marks 'processing' in one statement so no row lock is held
	// during the slow geocode/email network calls that follow.
	ClaimPendingIngestedForms(ctx context.Context, arg ClaimPendingIngestedFormsParams) ([]IngestedForm, error)
	GetIngestedFormByApplicationReference(ctx context.Context, applicationReference string) (IngestedForm, error)
	GetTransformedFormByApplicationReference(ctx context.Context, applicationReference string) (TransformedForm, error)
	// No row returned (pgx.ErrNoRows) means application_reference already
	// existed — a duplicate delivery, dropped silently (first-write-wins).
	InsertIngestedForm(ctx context.Context, arg InsertIngestedFormParams) (IngestedForm, error)
	// ON CONFLICT DO NOTHING is belt-and-braces alongside SKIP LOCKED and the
	// ingested_form_id/application_reference unique constraints — this should
	// never actually conflict in practice.
	InsertTransformedForm(ctx context.Context, arg InsertTransformedFormParams) (TransformedForm, error)
	MarkIngestedFormFailed(ctx context.Context, arg MarkIngestedFormFailedParams) error
	MarkIngestedFormSucceeded(ctx context.Context, id int64) error
	MarkTransformedFormEmailed(ctx context.Context, id int64) error
	Ping(ctx context.Context) (int32, error)
	// Resets rows orphaned by a worker crash mid-row (claimed but never
	// finished) back to 'pending' after they've sat in 'processing' too long.
	ReclaimStaleProcessing(ctx context.Context, staleAfter pgtype.Interval) (int64, error)
	// Only a 'failed' row can be retried; raw_payload is untouched, so the next
	// worker pass re-parses it with whatever code fix has since shipped.
	// attempt_count is reset so the claim query's attempt_count < max_attempts
	// filter doesn't skip a row that had already hit max_attempts.
	RequeueForRetry(ctx context.Context, applicationReference string) (IngestedForm, error)
}

var _ Querier = (*Queries)(nil)
