// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transformed_forms.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransformedFormByApplicationReference = `-- name: GetTransformedFormByApplicationReference :one
SELECT id, ingested_form_id, application_reference, session_id, first_name, last_name, email, gender, date_of_birth, phone_number, mobile_number, address_line_1, address_line_2, address_line_3, postcode, country, longitude, latitude, emailed_at, ready_at, created_at FROM transformed_forms
WHERE application_reference = $1
`

func (q *Queries) GetTransformedFormByApplicationReference(ctx context.Context, applicationReference string) (TransformedForm, error) {
	row := q.db.QueryRow(ctx, getTransformedFormByApplicationReference, applicationReference)
	var i TransformedForm
	err := row.Scan(
		&i.ID,
		&i.IngestedFormID,
		&i.ApplicationReference,
		&i.SessionID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Gender,
		&i.DateOfBirth,
		&i.PhoneNumber,
		&i.MobileNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressLine3,
		&i.Postcode,
		&i.Country,
		&i.Longitude,
		&i.Latitude,
		&i.EmailedAt,
		&i.ReadyAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransformedForm = `-- name: InsertTransformedForm :one
INSERT INTO transformed_forms (
    ingested_form_id, application_reference, session_id,
    first_name, last_name, email, gender, date_of_birth,
    phone_number, mobile_number,
    address_line_1, address_line_2, address_line_3, postcode, country,
    longitude, latitude
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17
)
ON CONFLICT (application_reference) DO NOTHING
RETURNING id, ingested_form_id, application_reference, session_id, first_name, last_name, email, gender, date_of_birth, phone_number, mobile_number, address_line_1, address_line_2, address_line_3, postcode, country, longitude, latitude, emailed_at, ready_at, created_at
`

type InsertTransformedFormParams struct {
	IngestedFormID       int64       `json:"ingested_form_id"`
	ApplicationReference string      `json:"application_reference"`
	SessionID            string      `json:"session_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Email                string      `json:"email"`
	Gender               string      `json:"gender"`
	DateOfBirth          pgtype.Date `json:"date_of_birth"`
	PhoneNumber          pgtype.Text `json:"phone_number"`
	MobileNumber         string      `json:"mobile_number"`
	AddressLine1         string      `json:"address_line_1"`
	AddressLine2         string      `json:"address_line_2"`
	AddressLine3         pgtype.Text `json:"address_line_3"`
	Postcode             string      `json:"postcode"`
	Country              string      `json:"country"`
	Longitude            float64     `json:"longitude"`
	Latitude             float64     `json:"latitude"`
}

// ON CONFLICT DO NOTHING is belt-and-braces alongside SKIP LOCKED and the
// ingested_form_id/application_reference unique constraints — this should
// never actually conflict in practice.
func (q *Queries) InsertTransformedForm(ctx context.Context, arg InsertTransformedFormParams) (TransformedForm, error) {
	row := q.db.QueryRow(ctx, insertTransformedForm,
		arg.IngestedFormID,
		arg.ApplicationReference,
		arg.SessionID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.MobileNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressLine3,
		arg.Postcode,
		arg.Country,
		arg.Longitude,
		arg.Latitude,
	)
	var i TransformedForm
	err := row.Scan(
		&i.ID,
		&i.IngestedFormID,
		&i.ApplicationReference,
		&i.SessionID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Gender,
		&i.DateOfBirth,
		&i.PhoneNumber,
		&i.MobileNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressLine3,
		&i.Postcode,
		&i.Country,
		&i.Longitude,
		&i.Latitude,
		&i.EmailedAt,
		&i.ReadyAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTransformedFormEmailed = `-- name: MarkTransformedFormEmailed :exec
UPDATE transformed_forms
SET emailed_at = now()
WHERE id = $1 AND emailed_at IS NULL
`

func (q *Queries) MarkTransformedFormEmailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markTransformedFormEmailed, id)
	return err
}
